### ISSUE TITLE
FoundryVTT v.9 Issue

### ISSUE THREAD

**Issue by MrBrentRogers** [casualchameleon/Bellows#53] opened 2021-12-21 04:45 UTC
Breaks UI - Sidebar Tabs moves from side to middle of screen when Bellows module enabled.

**Comment by MrBrentRogers** [comment] 2021-12-21 04:46
The Sidebar Tabs moves around as you start playing tracks

**Comment by cojinx303** [comment] 2021-12-21 09:18
Verified. Tried with all other modules deactivated and Bellows on its own caused this behavior. At first sidebar appears fine, but after clicking it it pops to just right of the center of the screen, and the blue % map zoom bar up top shrinks to have the toolbar as its new right margin. Also, the Configure Settings button becomes inoperable after the toolbar has moved.

**Comment by MN88** [comment] 2021-12-24 01:26
I get the following console error when trying to import playlists:

Bellows ERR | TypeError: s.createEmbeddedEntity is not a function
    at a.createFoundryVTTPlaylist (modules/bellows/bellows.js:1)
    at async s._updateObject (modules/bellows/bellows.js:1)
    at async s._onSubmit (foundry.js:3822)
LogError @ bellows.js:1
keybindings.js:104 Uncaught TypeError: game.keyboard.getKey is not a function
[Detected 1 package: pointer]
    at checkKey (modules/pointer/js/keybindings.js:104)
    at onPointerDown (modules/pointer/js/keybindings.js:123)

**Comment by anoverga17** [comment] 2021-12-25 01:06
I've tested this on a fresh world with just Bellows installed. I think the problem is the iframe player is not properly hidden and thus, the iframe player "pushes" the sidebar to the middle. 

This solution is a bit redundant but for those who need a quick fix, replacing the `div.yt-player` property in the styles/bellows.css file with the following seems to work for me:
```
.yt-player {
	position: absolute; 
	width:0; 
	height:0; 
	border:0;
	display: none;
}
```

**Comment by casualchameleon** [comment] 2021-12-26 00:01
Thanks @anoverga17. The code behind the player is inherited from the original musicassist repository and I haven't really tried to fix it.

Ideally I want the option to show/hide it built into the UI. I have a half finished bit of work that moves the player into a UI element that you can then minimise if you want. It'll have the YT controls and bring bellows more in line with the ToS.

I haven't had time for DnD let alone developing bellows recently but I plan to revisit it soon.

In the meantime if you create a PR with that code I'll get that merged and released as a bandaid fix. 

I haven't looked at other issues but it looks like there are quite a few that need attention. I'll see if I can do any triage at the same time if they're minor fixes.

Thanks

**Comment by cojinx303** [comment] 2021-12-26 02:19
> This solution is a bit redundant but for those who need a quick fix, replacing the `div.yt-player` property in the styles/bellows.css file with the following seems to work for me:
> 

It did indeed! Thanks much!

**Closed** 2021-12-26 10:05 UTC
